# Generated by Django 2.2 on 2019-12-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=250)),
                ('auther', models.CharField(max_length=250)),
                ('msg', models.TextField()),
            ],
        ),
    ]
